---
title: "Recent publications"
slug: "publications"
description: "A list of our most recent publications"
---

## 2019

- BOTHA A, LEASE HM, FULLER A, MITCHELL D, HETEM RS. Biologging as a method to remotely detect orientation to solar radiation in black and blue wildebeest. _Journal of Experimental Zoology_ **331**: 267-279, 2019. DOI: [10.1002/jez.2267](https://doi.org/10.1002/jez.2267){target="_blank"}

- FONSECA VDFC, MAIA ASC, SARAIVA EP, DE MELO COSTA CC, SILVA RG, ABDOUN KA, ALHAIDARY A, SAMARA EM, FULLER A. Bio-thermal responses and heat balance of a hair coat sheep breed raised under an equatorial semi-arid environment. _Journal of Thermal Biology_ **84**:83-91, 2019. DOI: [10.1016/j.jtherbio.2019.05.024](https://doi.org/10.1016/j.jtherbio.2019.05.024){target="_blank"}

- FONSECA VFC, SARAIVA EP, MAIA ASC, DE MELO COSTA CC, DOS SANTOS SGCG, MORAIS LKC, FULLER A, NETO MC. Training sheep for indirect calorimetry trials. _Small Ruminant Research_ **177**:36-43, 2019. DOI: [10.1016/j.smallrumres.2019.06.010](https://doi.org/10.1016/j.smallrumres.2019.06.010){target="_blank"}

- HETEM RS, MITCHELL D, DE WITT BA, FICK LG, MEYER LCR, MALONEY SK, FULLER A. Body temperature, activity patterns, and hunting in free-living cheetah: biologging reveals new insights. _Integrative Zoology_ **14**:30-47, 2019. DOI: [10.1111/1749-4877.12341](https://doi.org/10.1111/1749-4877.12341){target="_blank"}

- MALONEY S, GOH G, FULLER A, VESTERDORF K, BLACHE D. Amplitude of the circadian rhythm of temperature in homeotherms. _CAB Reviews: Perspectives in Agriculture, Veterinary Science, Nutrition and Natural Resources_ **14**: 1-30, 2019. DOI: [10.1079/PAVSNNR201914019](http://dx.doi.org/10.1079/PAVSNNR201914019){target="_blank"}

- SEYMOUR RS, HU Q, SNELLING EP, WHITE CR. Interspecific scaling of blood flow rates and arterial sizes in mammals. _Journal of Experimental Biology_ **222**: jeb199554, 2019. DOI: [10.1242/jeb.199554](https://doi.org/10.1242/jeb.199554){target="_blank"}

- SEYMOUR RS, SNELLING EP. Calculation and miscalculation of brain perfusion of primates.
_Journal of Human Evolution_ **128**: 99-102, 2019. DOI: [10.1016/j.jhevol.2018.06.001](https://doi.org/10.1016/j.jhevol.2018.06.001){target="_blank"}

- SNELLING EP, SEYMOUR RS, GIUSSANI DA, FULLER A, MALONEY SK, FARRELL AP, MITCHELL D, GEORGE K, DZIALOWSKI EM, JONKER SS, WUBE T. Scaling of cardiac morphology is interrupted by birth in the developing sheep Ovis aries. _Journal of Anatomy_ **235**: 96-105, 2019. DOI: [10.1111/joa.12990](https://doi.org/10.1111/joa.12990){target="_blank"}

- DA SILVA AL, DOS SANTOS SGCG, SARAIVA EP, FONSECA VDFC, GIVISIEZ PEN, PASCOAL LAF, MARTINS TDD, DE AMORIM MLCM. Supplementation of diets with glutamine and glutamic acid attenuated the effects of cold stress on intestinal mucosa and performance of weaned piglets. _Animal Production Science_, **in press**.

- DE AMORIM MLCM, SARAIVA EP, VDFC FONSECA, GUERRA RR, DOS SANTOS SGCG, ALMEIDA MEV, MALONEY SK. Coat and skin morphology of hair sheep breeds in an equatorial semi-arid environment. _Journal of Thermal Biology_, **in press**.


## 2018

- BUSS P, MILLER M, FULLER A, HAW A, STOUT E, OLEA-POPELKA F, MEYER LCR. 
Post-induction butorphanol administration alters oxygen consumption to improve blood gases in etorphine-immobilized white rhinoceros. _Veterinary Anaesthesia and Analgesia_ **45**:57-67, 2018. DOI:
[10.1016/j.vaa.2017.03.008](https://dx.doi.org/10.1016/j.vaa.2017.03.008){target="_blank"}

- HU Q, SNELLING E, SEYMOUR RS. Femoral bone perfusion during growth and locomotory development of the western grey kangaroo Macropus fuliginosus. _Journal of Experimental Biology_ **221**: jeb168625, 2018. DOI: [10.1242/jeb.168625](https://doi.org/10.1242/jeb.168625){target="_blank"}

- IZWAN A, SNELLING EP, SEYMOUR RS, MEYER LCR, FULLER A, HAW, A, MITCHELL D, FARRELL AP, COSTELLO M-A, MALONEY SK. Ameliorating the adverse cardiorespiratory effects of chemical immobilization by inducing general anaesthesia in sheep and goats: implications for physiological studies of large wild animals. _Journal of Comparative Physiology_ **188**: 991-1003, 2018. DOI: [10.1007/s00360-018-1184-z](https://doi.org/10.1007/s00360-018-1184-z){target="_blank"}

- MEYER LCR, FULLER A, HOFMEYR M, BUSS P, MILLER M, HAW A. Use of butorphanol and diprenorphine to counter respiratory impairment in the immobilised white rhinoceros _(Ceratotherium simum)_. _Journal of the South African Veterinary Association_ **89**: 1-8, 2018. DOI: [10.4102/jsava.v89i0.1683](https://doi.org/10.4102/jsava.v89i0.1683){target="_blank"}

- MINKNER MMI, YOUNG C, AMICI F, MCFARLAND R, BARRETT L, GROBLER JP, HENZI SP, WIDDIG A. Assessment of male reproductive skew via highly polymorphic STR markers in wild vervet monkey, _Chlorocebus pygerythrus_. _Journal of Heredity_ **109**: 780-790, 2018. DOI: [10.1093/jhered/esy048](https://doi.org/10.1093/jhered/esy048){target="_blank"}

- MITCHELL D. Conserving diggers: from gold miners to aardvarks. _Conservation Physiology_ **6**: coy024, 2018. DOI: [10.1093/conphys/coy024](https://doi.org/10.1093/conphys/coy024){target="_blank"}

- MITCHELL D, SNELLING EP, HETEM RS, MALONEY SK, STRAUSS WM, FULLER A. Revisiting concepts of thermal physiology: predicting responses of mammals to climate change. _Journal of Animal Ecology_, **87**: 956-973, 2018. DOI: [10.1111/1365-2656.12818](https://doi.org/10.1111/1365-2656.12818){target="_blank"}

- MOLE MA, DÁRAUJO SR, VAN AARDE RJ, MITCHELL D, FULLER. A Savanna elephants maintain homeothermy under African heat. _Journal of Comparative Physiology B_ **188**: 889-897, 2018. DOI: [10.1007/s00360-018-1170-5](https://doi.org/10.1007/s00360-018-1170-5){target="_blank"}

- SEYMOUR RS AND SNELLING E. Calculating brain perfusion of primates. _Journal of Human Evolution_ **in press**. DOI: [10.1016/j.jhevol.2018.06.001](https://doi.org/10.1016/j.jhevol.2018.06.001){target="_blank"}

- SNELLING EP, MALONEY SK, FARRELL AP, MEYER LCR, IZWAN A, FULLER A, MITCHELL D, HAW A, COSTELLO M-A, SEYMOUR RS. Scaling of morphology and ultrastructure of hearts among wild African antelope. _Journal of Experimental Biology_ **221**: jeb184713, 2018. DOI: [10.1242/jeb.184713](https://doi.org/10.1242/jeb.184713){target="_blank"}

## 2017

- BARNETT A, BRACCINI M, DUDGEON C, PAYNE N, ABRANTES KG, SHEAVES M, SNELLING E. The utility of bioenergetics modeling in quantifying predation rates of marine apex predators: ecological and fisheries implications. _Scientifc Reports_ **7**: 12982. DOI: [10.1038/s41598-017-13388-y](https://dx.doi.org/10.1038/s41598-017-13388-y){target="_blank"}

- DE LANGE SS, FULLER A, HAW A, HOFMEYR M, BUSS P, MILLER M, MEYER LCR.
Tremors in white rhinoceros (Ceratotherium simum) during etorphine-azaperone immobilization. 
_Journal of the South African Veterinary Association_ **88**: a1466, 2017. DOI [10.4102/jsava.v88i0.1466](https://dx.doi.org/10.4102/jsava.v88i0.1466){target="_blank"}

- HENZI SP, HETEM RS, FULLER A, MALONEY SK, YOUNG C, MITCHELL D, BARRETT L, McFARLAND R.
Consequence of sex-specific sociability for thermoregulation in male vervet monkeys during winter. _Journal of Zoology_ **302**: 193-200, 2017. DOI: [10.1111/jzo.12448](https://doi.org/10.1111/jzo.12448){target="_blank"}

- KIRCHHOF S, HETEM RS, LEASE LM, MILES DB, MITCHELL D, MÜLLER J, RÖDEL M, SINERVO B, WASSENAAR T, MURRAY IW. Thermoregulatory behavior and high thermal preference buffer impact of climate change in a Namib Desert lizard. _Ecosphere_ **8**: e02033, 2017. DOI: [10.1002/ecs2.2033](https://doi.org/10.1002/ecs2.2033){target="_blank"}

- MALONEY SK, MARSH MK, MCLEOD SR, FULLER A. Heterothermy is associated with reduced fitness in wild rabbits. _Biology Letters_ **13**: 20170521, 2017. DOI: [10.1098/rsbl.2017.0521](https://doi.org/10.1098/rsbl.2017.0521){target="_blank"}

- MITCHELL G, VAN SITTERT S, ROBERTS D, MITCHELL D. Body surface area and thermoregulation in giraffes. _Journal of Arid Environments_ **145**: 35-42, 2017. DOI: [10.1016/j.jaridenv.2017.05.005](https://doi.org/10.1016/j.jaridenv.2017.05.005){target="_blank"}

- REY B, DUCHAMP C, ROUSSEL D. Uncoupling effect of palmitate is exacerbated in skeletal muscle mitochondria of sea-acclimatized king penguins (Aptenodytes patagonicus). _Comparative Biochemistry and Physiology A_ **211**: 56-60, 2017. DOI: [10.1016/j.cbpa.2017.06.009](https://doi.org/10.1016/j.cbpa.2017.06.009){target="_blank"}

- REY B, FULLER A, MITCHELL D, MEYER LCR, HETEM RS. Drought-induced starvation of aardvarks in the Kalahari: an indirect effect of climate change. _Biology Letters_ **13**: 20170301, 2017. DOI: [10.1098/rsbl.2017.0301](https://dx.doi.org/10.1098/rsbl.2017.0301){target="_blank"}

- SNELLING EP, HU Q, TAGGART DA, FULLER A, MITCHELL D, FARRELL AP, MALONEY SK, SEYMOUR RS. Scaling of the ankle extensor muscle-tendon units and the biomechanical implications for bipedal hopping locomotion in the post-pouch kangaroo Macropus fuliginosus. _Journal of Anatomy_, **231**: 921-930, 2017. DOI: [10.1111/joa.12715](https://doi.org/10.1111/joa.12715){target="_blank"}

- STRAUSS WM, HETEM RS, MITCHELL D, MALONEY SK, O’BRIEN H, MEYER LCR, FULLER A. Body water conservation through selective brain cooling by the carotid rete: a physiological feature for surviving climate change? _Conservation Physiology_ **5**, 2017. DOI: [10.1093/conphys/cow078](https://doi.org/10.1093/conphys/cow078){target="_blank"}

- TRETHOWAN P, FULLER A, HAW A, HART T, MARKHAM A, LOVERIDGE AJ, HETEM R, DU PREEZ B, MACDONALD DW. Getting to the core: internal body temperatures help reveal the ecological function and thermal implications of the lions’ mane. _Ecology and Evolution_ **7**: 253-262, 2017. DOI: [10.1002/ece3.255](https://doi.org/10.1002/ece3.2556){target="_blank"}

- YOUNG C, GANSWINDT A, McFARLAND R, DE VILLIERS C, VAN HEERDEN J, GANSWINDT S, BARRETT L, HENZI SP. Faecal glucocorticoid metabolite monitoring as a measure of physiological stress in captive and wild vervet monkeys. _General and Comparative Endocrinology_, **253**:53-59, 2017. DOI: [10.1016/j.ygcen.2017.08.025](https://doi.org/10.1016/j.ygcen.2017.08.025){target="_blank"}


## 2016

- BUSS P, MILLER M, FULLER A, HAW A, WANTY R, OLEA-POPELKA F, MEYER L. Cardiovascular effects of etorphine, azaperone and butorphanol combinations in chemically immobilized captive white rhinoceros (Ceratotherium simum). _Journal of Zoo and Wildlife Medicine_ **47**:834-43, 2016. DOI: [10.1638/2015-0298.1](https://doi.org/10.1638/2015-0298.1){target="_blank"}

- CROWE-RIDDELL JM, SNELLING EP, WATSON AP, Kyuseop SUH A, PARTRIDGE C, SANDERS KL. The evolution of scale sensilla in the transition from land to sea in elapid snakes. _Open Biology_ **6**:160054, 2016. DOI: [10.1098/rsob.160054](https://doi.org/10.1098/rsob.160054){target="_blank"}

- FULLER A, MITCHELL D, MALONEY SK, HETEM RS. Towards a mechanistic understanding of the responses of large terrestrial mammals to heat and aridity associated with climate change. _Climate Change Responses_ **3**: 1-19, 2016. DOI: [10.1186/s40665-016-0024-1](https://doi.org/10.1186/s40665-016-0024-1){target="_blank"}

- HAW AJ, MEYER LCR, FULLER A. Nalbuphine and butorphanol reverse opioid-induced respiratory depression but increase arousal in etorphine-immobilized goats (Capra hircus). _Veterinary Anaesthesia and Analgesia_ **43**:539-48, 2016. DOI: [10.1111/vaa.12343](https://doi.org/10.1111/vaa.12343){target="_blank"}

- HAW AJ, MEYER LCR, GREER JJ, FULLER A. Ampakine CX1942 attenuates opioid-induced respiratory depression and corrects the hypoxaemic effects of etorphine in immobilized goats (Capra hircus). _Veterinary Anaesthesia and Analgesia_ **43**:528-38, 2016. DOI: [10.1111/vaa.12358](http://dx.doi.org/10.1111/vaa.12358){target="_blank"}

- HETEM RS, MALONEY SK, FULLER A, MITCHELL D. Heterothermy in large mammals: inevitable or implemented? _Biological Reviews_ **91**:187-205, 2016. DOI: [10.1111/brv.12166](https://doi.org/10.1111/brv.12166){target="_blank"}

- MCFARLAND R, HENZI P, BARRETT L, WANIGARATNE A, COETZEE E, FULLER A, HETEM RS, MITCHELL D, MALONEY SK. Thermal consequences of increased pelt loft infer an additional utilitarian function for grooming. _American Journal of Primatology_ **78**:456-61, 2016. DOI: [10.1002/ajp.22519](https://doi.org/10.1002/ajp.22519){target="_blank"}

- MOLE M, D'ARAUJO S, VAN AARDE R, MITCHELL D, FULLER A. Coping with heat: behavioural and physiological responses of savanna elephants in their natural habitat. _Conservation Physiology_ **4**:cow044, 2016. DOI: [10.1093%2Fconphys%2Fcow044](https://dx.doi.org/10.1093%2Fconphys%2Fcow044){target="_blank"}

- MURRAY IW, FULLER A, LEASE HM, MITCHELL D, HETEM RS. Ecological niche separation of two sympatric insectivorous lizard species in the Namib Desert. _Journal of Arid Environments_ **124**:225-32, 2016. DOI: [10.1016/j.jaridenv.2015.08.020](https://doi.org/10.1016/j.jaridenv.2015.08.020){target="_blank"}

- MURRAY IW, LEASE HM, HETEM RS, MITCHELL D, FULLER A, WOODBORNE S.
Stable isotope analysis of diet confirms niche separation of two sympatric species of Namib Desert lizard. _Integrative Zoology_ **11**:60–75, 2016. [10.1111/1749-4877.12170](https://doi.org/10.1111/1749-4877.12170){target="_blank"}

- REY B, FULLER A, HETEM RS, LEASE HM, MITCHELL D, MEYER LCR. 
Microchip transponder thermometry for monitoring core body temperature during capture of antelope. _Journal of Thermal Biology_ **55**:47-53, 2016. DOI: [10.1016/j.jtherbio.2015.11.010](https://doi.org/10.1016/j.jtherbio.2015.11.010){target="_blank"}

- REY B, DéGLETAGNE C, BODENNEC J, MONTERNIER P-A, MORTZ M, ROUSSEL D, ROMESTAING C, ROUANET J-L, TORNOS J, DUCHAMP C. Hormetic response triggers multifaceted anti-oxidant strategies in immature king penguins (Aptenodytes patagonicus). _Free Radical Biology and Medicine_ **97**:577-587, 2016. DOI: [10.1016/j.freeradbiomed.2016.07.015](https://doi.org/10.1016/j.freeradbiomed.2016.07.015){target="_blank"}

- SEYMOUR RX, BOSIOCIC V, SNELLING EP. Fossil skulls reveal that blood flow rate to the brain increased faster than brain volume during human evolution. _Royal Society Open Science_ **3**:160305, 2016. DOI: [10.1098/rsos.160305](https://doi.org/10.1098/rsos.160305){target="_blank"}

- SNELLING EP, SEYMOUR RS, GREEN JEF, MEYER LCR, FULLER A, HAW A, MITCHELL D, FARRELL AP, COSTELLO M-A, IZWAN A, BADENHORST M, MALONEY SK. A structure–function analysis of the left ventricle. _Journal of Applied Physiology_ **121**:900-909, 2016. DOI: [10.1152/japplphysiol.00435.2016](https://doi.org/10.1152/japplphysiol.00435.2016){target="_blank"}

- STRAUSS WM, HETEM RS, MITCHELL D, MALONEY SK, MEYER LCR, FULLER A. Three African antelope species with varying water dependencies exhibit similar selective brain cooling. _Journal of Comparative Physiology B_ **186**:527-40, 2016. DOI: [10.1007/s00360-016-0968-2](https://doi.org/10.1007/s00360-016-0968-2){target="_blank"}

- TRETHOWAN PD, HART T, LOVERIDGE AJ, HAW A, FULLER A, MACDONALD DW. Improved homeothermy and hypothermia in African lions during gestation. _Biology Letters_ **12**: 20160645, 2016. DOI: [10.1098/rsbl.2016.0645](https://doi.org/10.1098/rsbl.2016.0645){target="_blank"}
